import {
  Document,
  Page,
  PDFDownloadLink,
  View,
  Text,
  StyleSheet,
} from "@react-pdf/renderer";

const styles = StyleSheet.create({
  header: {
    fontSize: 12,
    marginBottom: 10,
    textAlign: "center",
  },
  footer: {
    fontSize: 8,
    marginTop: 8,
    textAlign: "center",
  },
  recipe: {
    fontSize: 10,
    margin: 8,
    textAlign: "center",
  },
});

function FilePdf ({ text })  {
  return (
  <Document>
    <Page size="A4">
      <View>
        <Text style={styles.header} fixed>
          Recipe from What to cook
        </Text>
      </View>
      <View>
        <Text style={styles.recipe}>{text}</Text>
      </View>
      <Text style={styles.footer} fixed>
        Generated by ChatGPT
      </Text>
    </Page>
  </Document>
);
}

export default function DownloadPdf({ recipe }) {
  return (
    <div>
      <PDFDownloadLink
        document={<FilePdf text={recipe} />}
        fileName="recipe.pdf"
      >
        <button className="recipe_button">
          <svg
            xmlns="http://www.w3.org/2000/svg"
            fill="none"
            viewBox="0 0 24 24"
            strokeWidth={1.5}
            stroke="currentColor"
            className="size-6"
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              d="M7.5 7.5h-.75A2.25 2.25 0 0 0 4.5 9.75v7.5a2.25 2.25 0 0 0 2.25 2.25h7.5a2.25 2.25 0 0 0 2.25-2.25v-7.5a2.25 2.25 0 0 0-2.25-2.25h-.75m-6 3.75 3 3m0 0 3-3m-3 3V1.5m6 9h.75a2.25 2.25 0 0 1 2.25 2.25v7.5a2.25 2.25 0 0 1-2.25 2.25h-7.5a2.25 2.25 0 0 1-2.25-2.25v-.75"
            />
          </svg>
        </button>
      </PDFDownloadLink>
    </div>
  );
}
